version: 2
jobs:
  build:
    docker:
      - image: rappdw/docker-java-python

    steps:
      - checkout            
      - run:
          name: install-requirements
          command: |
            pip install pipenv
            pipenv run pip freeze
            pip freeze
            bash <(curl -s https://scripts.scantist.com/staging/ci-circle.sh)
